app/cases/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Regexp


class CaseSearchForm(FlaskForm):
    """
    Form to lookup a case and get the sosreports
    """
    casenum = StringField('casenum',
                          validators=[DataRequired(),
                                      Regexp('^0[0-9]{7}$',
                                             message="Invalid case number")],
                          id='casenum')
    submit = SubmitField('Search')

app/cases/__init__.py
from flask import Blueprint

cases = Blueprint('cases', __name__)

from . import views

app/cases/views.py
# Flask
from flask import flash, redirect, render_template, url_for
from flask import current_app, request, jsonify
from flask_login import login_required

# Global imports
import os
import re
import datetime
import subprocess

# local imports
from . import cases
from forms import CaseSearchForm
from app.models import Report
from app.models import Check
from app import flash_errors
from app import db
from app.checks.helper import loop_checks, count_checks
from app.reports.helper import add_report
from app.helpers.history import create_event
from app.cases.helper import find_reports, magui


@cases.route('/<case>/yank?force=<force>')
@cases.route('/<case>/yank')
@login_required
def yank(case, force=None):
    """
    Yank files to collab-shell
    :param case: case id
    :param force: if true, we force the yank
    :return: redirect to /cases/caseid
    """
    create_event("yank", "case", [case])
    case = re.sub('^[0]*', '0', str(case))
    if force == 'True':
        command = "/bin/bash /usr/bin/yank " + case + " --force "
    else:
        command = "/bin/bash /usr/bin/yank " + case
    try:
        subprocess.check_output([command], shell=True)
    except subprocess.CalledProcessError as e:
        flash(u"Unable to yank case %s: %s" % (case, e.output),
              category="error")
    return redirect(url_for("cases.search", case=case), 303)


@cases.route('/', methods=['GET', 'POST'])
@cases.route('/<case>', methods=['GET'])
@login_required
def search(case=None):
    """
    Handle requests for cases
    :param case: case id
    :return: search.html
    """

    form = CaseSearchForm()
    if case is None and form.validate_on_submit():
        case = form.casenum.data
    if case is not None:
        casepath = current_app.config["CASES_PATH"] + "/" + case
        report_list = []
        # Folder doesn't exist, let's check the DB
        create_event("show", "case", [case])
        if os.path.isdir(casepath) is False:
            report_list = Report.query.filter(Report.case_id == case).all()
            if report_list is None or len(report_list) == 0:
                return render_template('cases/notfound.html', casenum=case), 404
            else:
                flash(u"Files for case %s are not found, but we have cached the metadata" % (case), category="warning")
        else:
            report_list = find_reports(casepath, case, current_app.config["REPORT_FILE_NAMES"])
            # We prepare to delete in case report has changed.
            report_delete = []
            for report in report_list:
                add_report_status = add_report(report)
                if report.changed is True:
                    report_delete.append(report.id)
                if add_report_status is not None:
                    return render_template('errors/generic-error.html', message=report.fullpath + ": " + add_report_status), 403

            # To make things faster, we need to bulk delete the
            # checks for the reports that have changed.
            if len(report_delete) > 0:
                Check.query.filter(Check.report_id.in_(report_delete)).delete(synchronize_session=False)

        for report in report_list:
            loop_checks(report, current_app)
            count = count_checks(report.id)
            # add report to the web interface
            report.icon = "cog"
            if report.source == "magui":
                report.icon = "microchip"
            report.setattrs(
                checks_total=count["total"],
                checks_fail=count[current_app.config["RC_FAILED"]],
                checks_skip=count[current_app.config["RC_SKIPPED"]],
                checks_okay=count[current_app.config["RC_OKAY"]])

            report.hr_size = report.get_hr_size()

        return render_template('cases/search.html', form=form, casenum=case, report_list=report_list)
    # There was an error with the form submission
    elif request.method == "POST":
        flash_errors(form)
    # If no caseid, we return standard form
    return render_template('cases/search.html')


@cases.route('/compare', methods=['POST', 'GET'])
@login_required
def compare():
    """
    Compare multiple reports
    :return: json object: status, msg
    """
    reports = request.get_json()
    if len(reports) < 2:
        return jsonify({"status": "danger",
                        "msg": "We need at least 2 reports to compare"})

    create_event("compare", "report", reports)
    rlist = []
    for r in reports:
        report = db.session.query(Report).filter_by(id=r).first()
        if report is None:
            return jsonify({"status": "danger", "msg": "Report not found"})
        rlist.append(os.path.dirname(report.path))
    outfile = re.match("(/cases/[0-9]+/)", rlist[0]).group(1) + "magui" + str(datetime.datetime.today().strftime('%Y%m%d%H%M%S')) + ".json"
    return magui(outfile, rlist, current_app.config["CITELLUS_PATH"])

app/templates/cases/modal.html
<div class="modal nx-check-list-modal" tabindex="-1" role="dialog" aria-labelledby="modal_check_list_title">
    <div class="modal-dialog modal-lg wizard-pf">

        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true" aria-label="Close">
                <span class="pficon pficon-close"></span>
              </button>
                <h4 class="modal-title nx-check-list-modal-title">Checks</h4>
            </div>
            <div class="modal-body nx-check-list-modal-body">
            </div>
            <!-- /modal-body -->
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">OK</button>
            </div>
            <!-- /modal-footer-->
        </div>
        <!-- /modal-content -->
    </div>
    <!-- /modal-dialog -->
</div>
<!-- /modal -->

app/templates/cases/notfound.html
{% extends "layout/base.html" %} 
{% set active_page = "cases" %} 
{% block title %}{{ casenum }} - Cases{% endblock %}
{% block body %} 
    <div class="row row-cards-pf">
        <div class="col-md-4 col-md-offset-4">
            <div class="card-pf card-pf-accented card-pf-aggregate-status">
                <h2 class="card-pf-title">
                    <span class="fa fa-question-circle"></span> Case {{ casenum }} not found
                </h2>
                <div class="card-pf-body">
                    <a href="{{ url_for('cases.yank', case = casenum, force = "True") }}" class="btn btn-success nx-btn-yank">Yank</a>
                    <a href="{{ config["CRM_CASE_URL"] }}{{ casenum }}" target="_blank" class="btn btn-primary nx-btn-crm">Salesforce</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %} 

app/templates/cases/search.html
{% extends "layout/base.html" %} 
{% set active_page = "cases" %} 
{% block title %}Cases{% endblock %} 
{% block body %} 
    {% include 'cases/modal.html' %} 
    {% if report_list is defined %}
        <div class="row toolbar-pf">
            <div class="col-sm-12">
                <form class="toolbar toolbar-pf-actions">
                    <div class="toolbar-pf-action-right">
                        <h5>{{ report_list|length}} reports</h5>
                    </div>
                    <div class="form-group toolbar-pf-filter">
                        <label class="sr-only" for="filter">Name</label>
                        <div class="input-group">
                            <input class="form-control nx-filter-text" data-type="reports" placeholder="Filter By Name..." type="search">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-btn">
                                <button type="button" 
                                        name="actions" class="btn btn-default dropdown-toggle nx-actions" 
                                                       data-toggle="dropdown" aria-haspopup="true" 
                                                                              aria-expanded="false">
                                    Actions <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a href="#" class="nx-actions">Compare</a></li>
                                    <li><a href="{{ url_for('cases.yank', case = casenum, force = "True") }}">Yank</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="dropdown btn-group">
                            <button type="button" name="sort-reports" 
                                                  class="btn btn-default dropdown-toggle nx-sort-item-btn" 
                                                  data-toggle="dropdown" 
                                                  aria-haspopup="true" 
                                                  aria-expanded="false"
                                                  data-sortfield="collect-time">
                                Sort <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                <li><a href="#" class="nx-sort-item" 
                                                data-key="collect-time">Date</a></li>
                                <li><a href="#" class="nx-sort-item"
                                                data-key="machine-id">System UUID</a></li>
                                <li><a href="#" class="nx-sort-item"
                                                data-key="name">Server Name</a></li>
                                <li><a href="#" class="nx-sort-item"
                                                data-key="size">Size</a></li>
                            </ul>
                        </div>
                        <button class="btn btn-link nx-sort-direction" data-direction="desc" type="button">
                            <span class="fa fa-sort-amount-desc"></span>
                        </button>
                    </div>
            </div>
        </div>
        <!-- /row -->
    {% else %}
        Type a case number in the search box above.
    {% endif %}


    <div class="list-group list-view-pf list-view-pf-view nx-list-group">
        {% for r in report_list %}
            <div class="list-group-item" data-name="{{ r['name'] }}" data-source="{{ r['source'] }}"
                                         data-collect-time="{{ r['collect_time'] }}" data-size="{{ r['size'] }}" 
                                         data-machine-id="{{ r['machine_id'] }}"> 
                <div class="list-view-pf-checkbox">
                    <input type="checkbox" {% if r['source'] == 'magui' %} disabled{% endif %} data-report-id="{{ r['id'] }}">
                </div><!-- /list-view-pf-checkbox -->
                <div class="list-view-pf-actions">
                    <div class="dropdown pull-right dropdown-kebab-pf">
                        <button class="btn btn-link dropdown-toggle" 
                                type="button" id="dropdownKebabRight9" 
                                              data-toggle="dropdown" aria-haspopup="true" 
                                                                     aria-expanded="true">
                            <span class="fa fa-ellipsis-v"></span>
                        </button>
                        <ul class="dropdown-menu dropdown-menu-right" 
                            aria-labelledby="dropdownKebabRight9">
                            <li><a href="{{ url_for('reports.display_checks', report_id = r['id']) }}">Checks</a></li> 
                            <li role="separator" class="divider"></li>
                            <li><a href="{{ url_for('metrics.display_metrics', report_id = r['id']) }}">Metrics</a></li>
                            <li><a href="{{ url_for('health.display_health', report_id = r['id']) }}">Health</a></li>
                        </ul>
                    </div>
                    <!-- /dropdown -->
                </div>
                <!-- /list-view-pf-actions -->
                <div class="list-view-pf-main-info">
                    <div class="list-view-pf-left">
                        <span class="fa fa-{{ r['icon'] }} list-view-pf-icon-sm"></span>
                    </div>
                    <!-- /list-view-pf-left -->
                    <div class="list-view-pf-body" data-report-id="{{ r['id'] }}">
                        <div class="list-view-pf-description">
                            <div class="list-group-item-heading timestamp-heading">
                                <span title="Date that the sosreport was executed">{{ r['collect_time'] }}</span>
                            </div>
                            <div class="list-group-item-heading">
                                <a href="{{ url_for('reports.display_checks', report_id = r['id']) }}">{{ r['name'] }}</a>
                            </div>
                        </div><!-- /list-view-pf-description -->
                        <div class="list-view-pf-additional-info">
                            <div class="list-view-pf-additional-info-item">
                                <div class="list-view-pf-expand nx-view-all-checks">
                                    <div class="list-view-pf-additional-info-item">
                                        <span class="fa fa-clock-o" title="Citellus Analysis time"></span>
                                        <strong>{{ r['analyze_duration'] }}</strong>s
                                    </div>
                                </div>
                            </div>
                            <div class="list-view-pf-additional-info-item">
                                <div class="list-view-pf-expand nx-view-all-checks">
                                    <span class="fa fa-angle-right"></span>
                                    <span class="fa fa-cubes"></span>
                                    <strong><a href="{{ url_for('reports.display_checks', report_id = r['id']) }}">{{ r['checks_total'] }}</a></strong> Checks
                                </div>
                            </div>

                            <!-- /list-view-pf-additional-info-item -->
                            <div class="list-view-pf-additional-info-item">
                                <div class="list-view-pf-expand nx-check-count" data-type="RC_FAILED">
                                    <span class="fa fa-angle-right"></span>
                                    <span class="pficon pficon-error-circle-o"></span>
                                    <strong>{{ r['checks_fail'] }}</strong> Failed
                                </div>

                            </div>
                            <!-- /list-view-pf-additional-info-item -->
                            <div class="list-view-pf-additional-info-item">
                                <div class="list-view-pf-expand nx-check-count" data-type="RC_SKIPPED">
                                    <span class="fa fa-angle-right"></span>
                                    <span class="pficon pficon-help"></span>
                                    <strong>{{ r['checks_skip'] }}</strong> Skipped
                                </div>
                            </div>
                            <!-- /list-view-pf-additional-info-item -->
                            <div class="list-view-pf-additional-info-item">
                                <div class="list-view-pf-expand nx-check-count" data-type="RC_OKAY">
                                    <span class="fa fa-angle-right"></span>
                                    <span class="fa fa-check-circle-o"></span>
                                    <strong>{{ r['checks_okay'] }}</strong> Okay
                                </div>
                            </div>
                            <!-- /list-view-pf-additional-info-item -->
                            <div class="list-view-pf-additional-info-item">
                                <span class="fa fa-microchip"></span>
                                <strong>{{ r['source'] }}</strong>
                            </div>
                            <!-- /list-view-pf-additional-info-item -->
                            <div class="list-view-pf-additional-info-item">
                                <span class="fa fa-hdd-o"></span>
                                <strong>{{ r['hr_size'] }}</strong>
                            </div>
                            <!-- /list-view-pf-additional-info-item -->
                            <div class="list-view-pf-additional-info-item">
                                <div class="list-view-pf-expand nx-show-metrics">
                                    <span class="fa fa-line-chart"></span>
                                    <strong>{{ r['sarfiles']|length }} days</strong>
                                </div>
                            </div>
                            <!-- /list-view-pf-additional-info-item -->
                        </div>
                        <!-- /list-view-pf-additional-info -->
                    </div>
                    <!-- /list-view-pf-body -->
                </div>
                <!-- /list-view-pf-main-info -->
            </div>
            <!-- /list-group-item -->
        {% endfor %} 
    </div>
{% endblock %} 
{% block javascript %}
    {% include "layout/toolbar.html" %}
{% endblock %}

app/templates/cases/search_form.html
<!-- removing this file as we will only use the hader for searching cases, this is not important anymore. Robin-->
<div class="row">
    <form class="form-horizontal" method="post" action="{{ config['APPLICATION_ROOT'] }}/cases/" role="form">
        {{ form.csrf_token }}
        <div class="form-group">
            <label for="casenum" class="col-sm-3 col-md-3 control-label">Case Number</label>
            <div class="col-sm-3 col-md-3">
                {{ form.casenum(class='form-control', placeholder='02000000') }}
            </div>
            <!-- /col -->
            <div class="col-sm-3 col-md-3">
                <button type="submit" class="btn btn-primary btn-lg" tabindex="4">Search</button>
            </div>
            <!-- /col -->
        </div>
        <!-- /form-group -->
    </form>
</div>
<!--/row-->

app/templates/cases/test.html
{% extends "layout/base.html" %}
{% block title %}Site Map{% endblock %}
{% block body %}
{% for r in out: %}
{{ r }}<br>
{% endfor %}
{% endblock %}