app/health/__init__.py
from flask import Blueprint

health = Blueprint('health', __name__)

from . import views

app/health/views.py
from flask import render_template, abort, jsonify
from flask_login import login_required

import logging

from . import health
from app.models import Report
from app.helpers.cpuinfo import Cpuinfo
from app.helpers.meminfo import Meminfo
from app.helpers.blockinfo import Blocks
from app.helpers.history import create_event


@health.route('/<report_id>', methods=['GET'])
@login_required
def display_health(report_id):
    report = Report.query.get(report_id)
    create_event("health", "report", [report_id])
    return render_template('health/show.html', report=report)
    """
    cpuinfo = cpuinfo.get_all_ratios(),
    meminfo = meminfo,
    mem_used = meminfo.ratio_mem_used(),
    hugepages_used = meminfo.ratio_hugepages_used(),
    swap_used = meminfo.ratio_swap_used(),
    io = blockinfo.get_list_io(),
    blocks = blockinfo.get_list_block(),
    inodes = blockinfo.get_list_inode()
    """


# placeholder route to allow the creation of /health/ url
@health.route('/', methods=['GET'])
@login_required
def index():
    return render_template('layout/not-ready.html')


def get_data(report_id):
    report = Report.query.get(report_id)
    if report is None:
        abort(404)
    return report


@health.route('/<report_id>/cpu_summary', methods=['GET'])
@login_required
def get_cpu_summary(report_id):
    report = get_data(report_id)
    cpuinfo = Cpuinfo(report)
    return jsonify(cpuinfo.get_all_ratios())


@health.route('/<report_id>/mem_summary', methods=['GET'])
@login_required
def get_mem_summary(report_id):
    report = get_data(report_id)
    try:
        meminfo = Meminfo(report)
        memory_used = round(meminfo.ratio_mem_used(), 2)
        swap_used = round(meminfo.ratio_swap_used(), 2)
        hugepages_used = round(meminfo.ratio_hugepages_used(), 2)
        return jsonify({
            "labels": ["Memory", "Swap", "HugePages"],
            "free": [100 - memory_used, 100 - swap_used, 100 - hugepages_used],
            "used": [memory_used, swap_used, hugepages_used]
        })
    except:
        return jsonify({})


@health.route('/<report_id>/mem_details', methods=['GET'])
@login_required
def get_mem_details(report_id):
    report = get_data(report_id)
    meminfo = Meminfo(report)
    meminfo.get()
    try:
        return jsonify([{"name": "Memory Available",
                         "value": meminfo.MemFree + meminfo.Buffers + meminfo.Cached + meminfo.Dirty + meminfo.AnonPages + meminfo.Slab + meminfo.VmallocUsed,
                         "children": [{"name": "MemFree", "value": meminfo.MemFree},
                                      {"name": "Buffers", "value": meminfo.Buffers},
                                      {"name": "Cached", "value": meminfo.Cached},
                                      {"name": "Dirty", "value": meminfo.Dirty},
                                      {"name": "AnonPages", "value": meminfo.AnonPages},
                                      {"name": "Slab", "value": meminfo.Slab},
                                      {"name": "VmallocUsed", "value": meminfo.VmallocUsed}]
                         },
                        {"name": "HugePages", "value": meminfo.HugePages_Total * meminfo.Hugepagesize,
                         "children": [{"name": "Free", "value": meminfo.HugePages_Free * meminfo.Hugepagesize},
                                      {"name": "Reserved", "value": meminfo.HugePages_Rsvd * meminfo.Hugepagesize},
                                      {"name": "Surplus", "value": meminfo.HugePages_Surp * meminfo.Hugepagesize}]
                         }])
    except AttributeError:
        return jsonify({})


@health.route('/<report_id>/blocks_io', methods=['GET'])
@login_required
def get_blocks_io(report_id):
    report = get_data(report_id)
    blocks = Blocks(report)
    blocks.list_io()
    out = []
    for o in blocks.data_table:
        out.append(blocks.data_table[o]["io"].dump())
    return jsonify(out)


@health.route('/<report_id>/blocks_space', methods=['GET'])
@login_required
def get_blocks_space(report_id):
    report = get_data(report_id)
    blocks = Blocks(report)
    blocks.list_block_space()
    out = []
    for o in blocks.data_table:
        try:
            out.append(blocks.data_table[o]["block"].dump())
        except KeyError:
            logging.debug(blocks.data_table[o])
    return jsonify(out)


@health.route('/<report_id>/blocks_inode', methods=['GET'])
@login_required
def get_blocks_inode(report_id):
    report = get_data(report_id)
    blocks = Blocks(report)
    blocks.list_inode_space()
    out = []
    for o in blocks.data_table:
        try:
            out.append(blocks.data_table[o]["inode"].dump())
        except KeyError:
            logging.debug(blocks.data_table[o])
    return jsonify(out)

app/templates/health/macros.html
{% macro div(id, title, source, type, width) %}
<div class="col-sm-{{ width }}">
    <div id="graph-{{ id }}" data-graph-title="{{ title }}" data-graph-source="Source: {{ source }}" data-graph-type="{{ type }}"></div>
</div>
{% endmacro %}

app/templates/health/show.html
{% extends"layout/base.html" %}
{% set active_page = "health" %}
{% block title %}Health{% endblock %}
{% block head %}
{{ super() }}
<style>
.highcharts-button-symbol {
    stroke: #666;
    stroke-width: 3px;
    fill: #E0E0E0;
}
.highcharts-menu {
    border: 1px solid #A0A0A0;
    background: #FFFFFF;
    padding: 5px 0;
    box-shadow: 3px 3px 10px #888;
}
.highcharts-menu-item {
    padding: 0 1em;
    background: none;
    color: #303030;
    cursor: pointer;
}
.highcharts-menu-item:hover {
    background: #4572A5;
    color: #FFFFFF;
}

</style>
{#
<link rel="stylesheet" type="text/css"
      href="https://cdnjs.cloudflare.com/ajax/libs/highcharts/6.0.7/css/highcharts.css"> #}
{% endblock %}
{% import "health/macros.html" as graph %}
{% import "reports/macros.html" as rdata %}
{% block body %}
{{ rdata.meta_table_html(report) }}

<h1>Server Health</h1>
<div class="row">
    {{ graph.div("memory-summary", "Memory Utilization", "/proc/meminfo", "bar", 3) }}
    {{ graph.div("memory-details", "Memory Utilization (Details)", "/proc/meminfo", "doughnut", 6) }}
    {{ graph.div("cpu-util-summary", "CPU Utilization", "/proc/stats", "doughnut", 3) }}
</div>
<div class="row">
    {{ graph.div("blocks-space", "Block Devices Space (G)", "df", "bar", 3) }}
    {{ graph.div("blocks-io", "Block Devices IO", "/proc/diskstats", "bar", 6) }}
    {{ graph.div("blocks-inode", "Block Devices Space (Inodes)", "df", "bar", 3) }}
</div>
{% endblock %}
{% block javascript %}
{{ rdata.meta_table_js() }}
<script src="https://cdnjs.cloudflare.com/ajax/libs/highcharts/6.0.7/highcharts.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/highcharts/6.0.7/js/modules/exporting.js"></script>
<script src="{{ config["APPLICATION_ROOT"] }}/static/js/highcharts.dark.js"></script>
<script type="text/javascript">
// Default options for stacked bar charts
var stackedBarOptions = {
    chart: { type: 'column' },
    xAxis: { categories: [] },
    yAxis: { 
        min: 0,
        stackLabels: { enabled: true, style: { fontWeight: 'bold', color: (Highcharts.theme && Highcharts.theme.textColor) || 'gray' } }
    },
    tooltip: {
        headerFormat: '<b>{point.x}</b><br/>',
        pointFormat: '{series.name}: {point.y}<br/>Total: {point.stackTotal}'
    },
    plotOptions: {
        column: {
            stacking: 'normal',
            dataLabels: { enabled: true, color: (Highcharts.theme && Highcharts.theme.dataLabelsColor) || 'white' }
        }
    }
};
 
function generateCPUChart(container) {
    var div = $("#" + container)
    // Highcharts options
    var options = {
       chart: { type: 'pie' },
       title: { text: div.data("graph-title") },
       subtitle: { text: div.data("graph-source") },
       tooltip: { pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>' },
       plotOptions: {
            pie: { 
                allowPointSelect: true, cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    style: { fontWeight: 'bold', color: 'white' }
                }
            },
       }
    };
    // Let's merge our theme with the options
    div.highcharts(Highcharts.merge(options, Highcharts.theme))
    // We need to have the chart object to push the series
    var chart = div.highcharts()
    // Getting the series
    $.ajax({
        url: '{{ url_for('health.index') }}{{ report.id }}/cpu_summary',
        dataType: "json",
        contentType: "text/plain; charset=utf-8",
        success: function(json) {
            var series = {
                id: 'series', name: div.data("graph-title"), innerSize: '50%', data: []
            }
            for (var propertyName in json) {
                series.data.push([propertyName, json[propertyName]]);
            }
            chart.addSeries(series);
        },
    });
}
function generateMemoryBarChart(container) {
    var div = $("#" + container)
    div.highcharts(Highcharts.merge(Highcharts.theme, stackedBarOptions))
    var chart = div.highcharts()
    chart.setTitle({ text: div.data("graph-title") }, { text: div.data("graph-source") }, true)
    chart.yAxis[0].setExtremes(0, 100);
    chart.yAxis[0].setTitle({ text: div.data("graph-title") })
    $.ajax({           
        url: '{{ url_for('health.index') }}{{ report.id }}/mem_summary',
        dataType: "json",       
        contentType: "text/plain; charset=utf-8",
        success: function(json) {
            chart.xAxis[0].setCategories(json["labels"]);
            var free = { id: 'free', name: "Free", data: json["free"]};
            var used = { id: 'used', name: "Used", data: json["used"]};
            chart.addSeries(free);
            chart.addSeries(used);
        },
    });      
}
function generateMemoryPieChart(container) {
    // We have to create the chart from within the ajax query here
    // because I didn't find a way to addSeries this kind of series
    var div = $("#" + container)
    var parentData = []
    var childrenData = []
    var options = []
    $.ajax({           
        url: '{{ url_for('health.index') }}{{ report.id }}/mem_details',
        dataType: "json",       
        contentType: "text/plain; charset=utf-8",
        success: function(json) {
            var categories = []
            $.each(json, function(index, value) {
                categories.push(value["name"]) 
                parentData.push({
                    name: value["name"], y: Math.round(value["value"] / 1024) / 100,
                })
                $.each(value["children"], function(cindex, cval) {
                    childrenData.push({
                        name: cval["name"], y: Math.round(cval["value"] / 1024) / 100,
                    })
                })
            })
            options = {
                chart: { type: 'pie' },
                title: { text: div.data("graph-title") },
                subtitle: { text: div.data("graph-source") },
                yAxis: { title: { text: 'Memory Utilization' }},
                plotOptions: { pie: { shadow: false, center: ['50%', '50%'] } },
                tooltip: { valueSuffix: 'MB' },
                series: [{
                    // MemAvailable + HugePages
                    name: 'Memory Type', data: parentData, size: '60%',
                    dataLabels: {
                        formatter: function () { return this.y > 5 ? this.point.name : null; },
                        color: '#ffffff', distance: -30
                    }
                }, {
                    name: 'Allocation', data: childrenData, size: '80%', innerSize: '60%',
                    dataLabels: {
                        formatter: function () { return this.y > 1 ? '<b>' + this.point.name + ':</b> ' + this.y + 'MB' : null; }
                    },
                }],
            };
            div.highcharts(Highcharts.merge(options, Highcharts.theme))
        },
    });
}

function generateBlockSpaceChart(container) {
    var div = $("#" + container)
    div.highcharts(Highcharts.merge(stackedBarOptions, Highcharts.theme, { tooltip: { pointFormat: '{series.name}: {point.y}G<br/>Total: {point.stackTotal}G' } }))
    var chart = div.highcharts()
    chart.setTitle({ text: div.data("graph-title") }, { text: div.data("graph-source") }, true)
    chart.yAxis[0].setTitle({ text: div.data("graph-title") })
    $.ajax({
        url: '{{ url_for('health.index') }}{{ report.id }}/blocks_space',
        dataType: "json",
        contentType: "text/plain; charset=utf-8",
        success: function(json) {
            var devices = []
            var free = []
            var used = []
            $.each(json, function(i,v) {
                devices.push(v["device_name"])
                free.push(Math.round(v["free"] / 1024 / 1024 * 100) / 100)
                used.push(Math.round(v["used"] / 1024 / 1024 * 100) / 100)
            })
            chart.xAxis[0].setCategories(devices);
            chart.addSeries({ id: 'free', name: 'Free', data: free})
            chart.addSeries({ id: 'used', name: 'Used', data: used})
        }
    });
}
 function generateBlockInodeChart(container) {
    var div = $("#" + container)
    div.highcharts(Highcharts.merge(stackedBarOptions, Highcharts.theme))
    var chart = div.highcharts()
    chart.setTitle({ text: div.data("graph-title") }, { text: div.data("graph-source") }, true)
    chart.yAxis[0].setTitle({ text: div.data("graph-title") })
    $.ajax({
        url: '{{ url_for('health.index') }}{{ report.id }}/blocks_inode',
        dataType: "json",
        contentType: "text/plain; charset=utf-8",
        success: function(json) {
            var devices = []
            var free = []
            var used = []
            $.each(json, function(i,v) {
                devices.push(v["device_name"])
                free.push(Math.round(v["free"] / 1024 / 1024 * 100) / 100)
                used.push(Math.round(v["used"] / 1024 / 1024 * 100) / 100)
            })
            chart.xAxis[0].setCategories(devices);
            chart.addSeries({ id: 'free', name: 'Free', data: free})
            chart.addSeries({ id: 'used', name: 'Used', data: used})
        }
    });
}
    // Let's merge our theme with the options
// div.highcharts(Highcharts.merge(options, Highcharts.theme))
    // We need to have the chart object to push the series
//    var chart = div.highcharts()
 function generateBlockIOChart(container) {
    var div = $("#" + container)
    div.highcharts(Highcharts.merge(stackedBarOptions, Highcharts.theme, { tooltip: { pointFormat: '{series.name}: {point.y}%<br/>Total: {point.stackTotal}%' } }))
    var chart = div.highcharts()
    chart.setTitle({ text: div.data("graph-title") }, { text: div.data("graph-source") }, true)
    chart.yAxis[0].setTitle({ text: div.data("graph-title") })
    var devices = []
    var read_completed_ratio = []
    var write_completed_ratio = []
    var read_merged_ratio = []
    var write_merged_ratio = []
    var read_ms_ratio = []
    var write_ms_ratio = []
    $.ajax({
        url: '{{ url_for('health.index') }}{{ report.id }}/blocks_io',
        dataType: "json",
        contentType: "text/plain; charset=utf-8",
        success: function(json) { 
            $.each(json, function(i,v) {
                devices.push(v["device_name"])
                total_completed = v["reads_completed"] + v["writes_completed"]
                total_merged = v["reads_merged"] + v["writes_merged"]
                total_ms = v["reading_ms"] + v["writing_ms"]
                read_completed_ratio.push(Math.round(v["reads_completed"] / total_completed * 10000) / 100)
                write_completed_ratio.push(Math.round(v["writes_completed"] / total_completed * 10000) / 100)
                read_merged_ratio.push(Math.round(v["reads_merged"] / total_merged * 10000) / 100)
                write_merged_ratio.push(Math.round(v["writes_merged"] / total_merged * 10000) / 100)
                read_ms_ratio.push(Math.round(v["reading_ms"] / total_ms * 10000) / 100)
                write_ms_ratio.push(Math.round(v["writing_ms"] / total_ms * 10000) / 100)
 
            })
            chart.xAxis[0].setCategories(devices);
            chart.addSeries({ id: 'read-completed', name: 'Reads Completed', data: read_completed_ratio, stack: 'completed'})
            chart.addSeries({ id: 'write-completed', name: 'Writes Completed', data: write_completed_ratio, stack: 'completed'})
            chart.addSeries({ id: 'read-merged', name: 'Reads Merged', data: read_merged_ratio, stack: 'merged'})
            chart.addSeries({ id: 'write-merged', name: 'Writes Merged', data: write_merged_ratio, stack: 'merged'})
            chart.addSeries({ id: 'read-ms', name: 'Reading milliseconds', data: read_ms_ratio, stack: 'ms'})
            chart.addSeries({ id: 'write-ms', name: 'Writing milliseconds', data: write_ms_ratio, stack: 'ms'})
        }
    });
}


generateMemoryBarChart("graph-memory-summary")
generateMemoryPieChart("graph-memory-details")
generateCPUChart("graph-cpu-util-summary")
generateBlockSpaceChart("graph-blocks-space")
generateBlockInodeChart("graph-blocks-inode")
generateBlockIOChart("graph-blocks-io")
</script>
{% endblock %}

app/templates/health/test.html
<!DOCTYPE html>
<html class="layout-pf layout-pf-fixed">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Nexus">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/daterangepicker.css') }}">

    <script src="{{ url_for('static', filename='js/jquery-1.11.3.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/moment.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/daterangepicker.js') }}"></script>
    <style>
        body {
            font-size: 15px;
            line-height: 1.6em;
            position: relative;
            margin: 0;
        }
        
        .container {
            width: 95%;
            max-width: 1260px;
        }
        
        p,
        pre {
            margin-bottom: 2em;
        }
        
        .main h2 {
            font-weight: bold;
            margin: 60px 0 20px 0;
        }
        
        .main h3 {
            margin: 60px 0 20px 0;
        }
        
        .main h4 {
            margin: 0 0 10px 0;
            font-weight: bold;
        }
        
        ul.nobullets {
            margin: 0;
            padding: 0;
            list-style-position: inside;
        }
        
        li {
            padding-bottom: 1em;
        }
        
        #sidebar {
            top: 20px;
            width: 300px;
        }
        
        #sidebar ul {
            margin-bottom: 5px;
        }
        
        #sidebar li {
            margin-bottom: 0;
            padding-bottom: 0;
        }
        
        #sidebar li ul {
            display: none;
        }
        
        #sidebar li.active ul {
            display: block;
        }
        
        #sidebar li li {
            padding: 4px 0;
        }
        
        input[type="text"] {
            padding: 6px;
            width: 100%;
            border-radius: 4px;
        }
        
        .navbar {
            text-align: left;
            margin: 0;
            border: 0;
        }
        
        .navbar-inverse {
            background: #ccc;
        }
        
        .navbar .container {
            padding: 0 20px;
        }
        
        .navbar-nav li a:link,
        .navbar-nav li a:visited {
            font-weight: bold;
            color: #fff;
            font-size: 16px;
        }
        
        .navbar-nav li {
            background: #fff;
        }
        
        .navbar-nav li a:hover {
            opacity: 0.8;
        }
        
        .navbar-nav li {
            padding: 0;
        }
        
        .navbar-inverse .navbar-text {
            margin: 18px 0 0 0;
            color: #eee;
        }
        
        #footer {
            background: #222;
            margin-top: 80px;
            padding: 30px;
            color: #fff;
            text-align: center;
        }
        
        #footer a:link,
        #footer a:visited {
            color: #fff;
            border-bottom: 1px dotted #fff;
        }
        
        #jumbo {
            background: #f5f5f5 linear-gradient(to bottom, #eee 0, #f5f5f5 100%);
            color: #000;
            padding: 30px 0;
            margin-bottom: 30px;
        }
        
        #jumbo .btn {
            border-radius: 0;
        }
        
        #config .demo {
            position: relative;
        }
        
        #config .demo i {
            position: absolute;
            bottom: 10px;
            right: 24px;
            top: auto;
            cursor: pointer;
        }
        
        #rightcol {
            margin-left: 330px;
        }
        
        #nav-spy {
            float: left;
            width: 300px;
        }
        
        @media (max-width: 980px) {
            #rightcol {
                margin-left: 0;
            }
            #nav-spy {
                float: none;
                position: relative;
            }
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-xs-12">
                <script src="https://gist.github.com/dangrossman/8e97e05e68cb683c4d71.js"></script>
            </div>
            <div class="col-md-4 col-xs-12">
                <h4>Demo:</h4>
                <input class="pull-right" type="text" name="daterange" value="01/15/2017 - 02/15/2017" />
            </div>
        </div>

        <script type="text/javascript">
            $(function() {
                $('input[name="daterange"]').daterangepicker();
            });
        </script>

    </div>

</body>